services:
  lach-sentinel:
    build: .
    container_name: lach-sentinel
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - ./data:/data
      - /proc:/host_proc:ro
      - /sys/class/thermal:/host_thermal:ro
      - /usr/local/emhttp/state:/host_state:ro
      - /mnt/user:/host_user:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NMAP_RANGE=192.168.111.0/24
      - NMAP_INTERVAL=3600
      - METRICS_INTERVAL=60
      - WS_PUSH_INTERVAL=5
      - TZ=Europe/Paris
    cap_add:
      - NET_ADMIN
      - NET_RAW
